'use client'

import Head from 'next/head'
import Cookies from "universal-cookie";
import React, { useState, useRef, useEffect } from "react";
import GenerateLetter from "./components/GenerateLetter";
import Login from "./components/Login";
import {auth} from '@/firebase'
import { Toaster } from "react-hot-toast";

const cookies = new Cookies();

export default function Home() {
  const [isAuth, setIsAuth] = useState(cookies.get("auth_user") || false);

    useEffect(() => {
    cookies.set("auth_user", isAuth);
  }, [isAuth]);

  //function to remove auth cookie and redirect to login page
  const logout = () =>{
    cookies.remove("auth_user");
    // reload the page
    window.location.reload();
  };



if (!isAuth) {
    return <div><Login setIsAuth={setIsAuth} /></div>;
  } else {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Toaster
        position="top-center"
        reverseOrder={false}
        gutter={8}
        containerClassName=""
        containerStyle={{}}
        toastOptions={{
          // Define default options
          className: '',
          duration: 5000,
          style: {
            background: '#363636',
            color: '#fff',
          },

          // Default options for specific types
          success: {
            duration: 5000,
            theme: {
              primary: 'green',
              secondary: 'black',
            },
          },
        }}
      />
      <div>
      <div className="w-screen h-screen">
      <div className="flex h-12 justify-between items-center p-8">
      <h1>Ai Coverletter Writer</h1>
      <div className='flex '>
        <img src={auth.currentUser?.photoURL} alt='logo' className='w-6 h-6'></img>        
        <h1>User: {auth.currentUser?.displayName}</h1>
      </div>
      <button onClick={logout}>Logout</button>        
      </div>
      {/* the generate letters component */}
      <GenerateLetter/>
      </div>
      </div>
      </div>
    </>
  )
}
}
